name: ServeRest API Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        cd Caio
        pip install -r requirements.txt
        
    - name: Run Robot Framework tests
      run: |
        cd Caio
        robot -d reports tests/
        
    - name: Upload test reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: robot-reports
        path: Caio/reports/
        
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: Caio/reports/output.xml